spring.application.name=appweb

# Puerto
server.port=8080

# H2 R2DBC
spring.r2dbc.url=r2dbc:h2:mem:///appwebdb
spring.r2dbc.username=sa
spring.r2dbc.password=

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Inicializar scripts SQL
spring.sql.init.mode=always

# Logs SQL
logging.level.org.springframework.r2dbc=DEBUG

spring.datasource.url=jdbc:h2:mem:appwebdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=